### ISSUE TITLE
analizar problemas de novas versões do GRPC > 1.6.0

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_ssm_api#99]
Editar o arquivo requirements/base.txt

Trocar: 

```
grpcio==1.6.0
grpcio-tools==1.6.0
grpcio-health-checking==1.6.0
```

Para

```
grpcio==1.7.3
grpcio-tools==1.7.3
grpcio-health-checking==1.7.3
```

Instalar as dependências: 

```
pip install -r requirements/local.txt
```

Tentar rodar o servidor grpc: 

```
python manage.py grpc_server
```

Erro: 

```
Starting GRPC... Host: [::], Port: 5000
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/jamil/projects/opac_ssm/grpc_ssm/management/commands/grpc_server.py", line 20, in handle
    settings.GRPC_MAX_SEND_MESSAGE_LENGTH)
  File "/Users/jamil/projects/opac_ssm/grpc_ssm/grpc_server.py", line 288, in serve
    health_pb2.add_HealthServicer_to_server(servicer, server)
AttributeError: module 'grpc_health.v1.health_pb2' has no attribute 'add_HealthServicer_to_server'
```

**Comment by jamilatta** [comment]
Editar o arquivo requirements/base.txt

Trocar: 

```
grpcio==1.6.0
grpcio-tools==1.6.0
grpcio-health-checking==1.6.0
```

Para

```
grpcio==1.7.3
grpcio-tools==1.7.3
grpcio-health-checking==1.7.3
```

Instalar as dependências: 

```
pip install -r requirements/local.txt
```

Tentar rodar o servidor grpc: 

```
python manage.py grpc_server
```

Erro: 

```
Starting GRPC... Host: [::], Port: 5000
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jamil/.virtualenvs/opac_ssm/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/jamil/projects/opac_ssm/grpc_ssm/management/commands/grpc_server.py", line 20, in handle
    settings.GRPC_MAX_SEND_MESSAGE_LENGTH)
  File "/Users/jamil/projects/opac_ssm/grpc_ssm/grpc_server.py", line 288, in serve
    health_pb2.add_HealthServicer_to_server(servicer, server)
AttributeError: module 'grpc_health.v1.health_pb2' has no attribute 'add_HealthServicer_to_server'
```

**Comment by jfunez** [comment]
Resolvido em:  https://github.com/scieloorg/opac_ssm_api/pull/184
